title: Mirko Mancin
email: mirko.mancin@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Di tutto e un po' riguardo IoT/AR e Industria 4.0
baseurl: "/" # the subpath of your site, e.g. /blog
url: "http://mirkomancin.github.io/" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  mirkomancin
paginate:         5
paginate_path:    '/page/:num'
permalink:        '/:year/:month/:title/'
excerpt_separator: ""
license:
  link:           'https://creativecommons.org/licenses/by-nc/3.0/'
  label:          'CC BY-NC'
author:           Mirko Mancin

# Build settings
#theme: minima
theme: jekyll-theme-clean-blog

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
